/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { InternetDefinition } from '../../..';
import emoji from './emoji';
import http_status_code from './http_status_code';
import jwt_algorithm from './jwt_algorithm';
import user_agent from './user_agent';

const internet: InternetDefinition = {
  emoji,
  http_status_code,
  jwt_algorithm,
  user_agent,
};

export default internet;
