name: Integration Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # weekly on Mondays at 03:00

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Set node version to 22
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Build
        run: pnpm run build

      - name: Integration Test
        run: pnpm run integration-test
